package buscaminas;

import javax.swing.JOptionPane;

/**
 *
 * @author monto
 */
@SuppressWarnings("serial")
public class Menu extends javax.swing.JFrame {

	GUI interfaz;

	/**
	 * Creates new form Menú
	 */
	public Menu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		principiante = new javax.swing.JButton();
		intermedio = new javax.swing.JButton();
		personalizado = new javax.swing.JButton();
		avanzado = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		jLabel1.setText("Buscaminas");

		principiante.setText("Principiante");
		principiante.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				principianteActionPerformed(evt);
			}
		});

		intermedio.setText("Intermedio");
		intermedio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				intermedioActionPerformed(evt);
			}
		});

		personalizado.setText("Personalizado");
		personalizado.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				personalizadoActionPerformed(evt);
			}
		});

		avanzado.setText("Avanzado");
		avanzado.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				avanzadoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(33, 33, 33)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(avanzado, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(personalizado, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(principiante, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(intermedio, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(layout.createSequentialGroup().addGap(51, 51, 51).addComponent(jLabel1)))
				.addContainerGap(44, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(27, 27, 27).addComponent(jLabel1).addGap(29, 29, 29)
						.addComponent(principiante)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(intermedio)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(avanzado)
						.addGap(11, 11, 11).addComponent(personalizado).addContainerGap(26, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Si se hace click en el boton principiante se asigna el nivel 1
	 * 
	 * @param evt Evento enviado por el boton.
	 */
	private void principianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_principianteActionPerformed
		int[] v = new int[18];
		interfaz = new GUI();
		interfaz.seleccionNivel(1);
		interfaz.setVisible(true);
		interfaz.setLocationRelativeTo(null);

	}// GEN-LAST:event_principianteActionPerformed

	/**
	 * Si se hace click en el boton intermedio se asigna el nivel 2
	 * 
	 * @param evt Evento enviado por el boton.
	 */
	private void intermedioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_intermedioActionPerformed
		interfaz = new GUI();
		interfaz.seleccionNivel(2);
		interfaz.setVisible(true);
		interfaz.setLocationRelativeTo(null);

	}// GEN-LAST:event_intermedioActionPerformed

	/**
	 * Si se hace click en el boton avanzado se asigna el nivel 3
	 * 
	 * @param evt Evento enviado por el boton.
	 */
	private void avanzadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_avanzadoActionPerformed
		interfaz = new GUI();
		interfaz.seleccionNivel(3);
		interfaz.setVisible(true);
		interfaz.setLocationRelativeTo(null);
	}// GEN-LAST:event_avanzadoActionPerformed

	/**
	 * Si se hace click en el boton personalizado se asigna el nivel 4 y se pregunta
	 * el tamaño deseado para el juego
	 * 
	 * @param evt Evento enviado por el boton.
	 */
	private void personalizadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_personalizadoActionPerformed

		// Se indica cual es el limite Para cada uno de los parametros
		JOptionPane.showMessageDialog(null,
				"El maximo tamaño del tablero es 30X30.\nEl numero de minas debe ser menor que el total de casillas y mayor que 0",
				"Instrucciones", JOptionPane.OK_OPTION);

		int filas = 0;
		int columnas = 0;
		int minas = 0;

		try {
			// Se preguntan las dimensiones deseadas
			filas = Integer.parseInt(JOptionPane.showInputDialog("ingrese el numero de filas que desea"));
			columnas = Integer.parseInt(JOptionPane.showInputDialog("ingrese el numero de filas que desea"));
			minas = Integer.parseInt(JOptionPane.showInputDialog("ingrese el numero de minas que desea"));
		} catch (NumberFormatException e) {
			// si se ingresa un caracter no numerico se informa al usuario
			JOptionPane.showMessageDialog(null, "Se ingresaron caracteres no validos, intentalo nuevamente");
			return;
		}

		// En caso de que alguno de los valores exceda los limites se informa al usuario
		if (filas > 30) {
			JOptionPane.showMessageDialog(null, "Recuerda que el numero de filas no debe ser mayor a 30");
			return;
		} else if (columnas > 30) {
			JOptionPane.showMessageDialog(null, "Recuerda que el numero de columnas no debe ser mayor a 30");
			return;
		} else if (minas >= (filas * columnas)) {
			JOptionPane.showMessageDialog(null,
					"Recuerda que el numero de minas no debe ser mayor al numero de casillas");
			return;
		} else if (minas < 1) {
			JOptionPane.showMessageDialog(null, "Recuerda que el numero de minas debe ser mayor que 0");
			return;
		}

		// Se inicializa la interfaz y se asigna el nivel
		interfaz = new GUI();
		interfaz.setVisible(true);
		interfaz.setLocationRelativeTo(null);
		interfaz.filasP = filas;
		interfaz.columnasP = columnas;
		interfaz.minasP = minas;
		interfaz.seleccionNivel(4);
	}// GEN-LAST:event_personalizadoActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton avanzado;
	private javax.swing.JButton intermedio;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton personalizado;
	private javax.swing.JButton principiante;
	// End of variables declaration//GEN-END:variables
	
}
